config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :artifacts
  resources :tenants do #Will generate the routes as /tenants/:tenant_id/projects
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  resources :members
  get 'home/index'
  root :to => "home#index"

  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions",
    :passwords => "milia/passwords",
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/common/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" id="nb">
      <div class="lines">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="container">
      </div>
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to(root_path, class: "navbar-brand") do %>
            <%= image_tag('icon.png', class:'header-icon') + 'EdTechSaaS'.html_safe %>
        <% end %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-right col-md-4">
            <% if current_user && current_user.is_admin? %>
              <%= link_to "<i class='fa fa-users'></i>  Add Members".html_safe,new_member_path,class: 'button-35 member' %>
              <%= link_to "<i class='fa fa-briefcase'></i>      Change Plan".html_safe,edit_plan_path,class: 'button-35 plan-icon' %>
              <li class="col-md-8 user-name">
              <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>
              </li>
              <li class="col-md-1"> </li>
              <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
            <% elsif current_user %>
               <li class="col-md-8 user-name">
              <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>
              </li>
               <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
            <% else %>
              <% if current_page?(root_path)%> <%# Root page - Signup options on the page, signin in the header%>
                  <li class="col-md-4 pull-right">
                  <%= link_to('Sign In', new_user_session_path, class: 'button-35 aa', title: 'Sign In') %>
                  </li>
              <%else%> <%# Not the root page %>
                  <li class="col-md-4 pull-right">
                  <%if current_page?(new_user_session_path)%>
                    <%= link_to('Sign Up', new_user_registration_path, class: 'button-35 aa', title: 'Sign ') %>
                  <%else%>
                    <%= link_to('Sign In', new_user_session_path, class: 'button-35 aa', title: 'Sign ') %>
                  <%end%>
                  </li>
              <%end%>
            <% end %>
          </ul>
        </div>
      </div>
</div>